insert into etiquettes (id, nom) values (1, 'végétarien');
insert into etiquettes (id, nom) values (2, 'poisson');
insert into etiquettes (id, nom) values (3, 'bœuf');
insert into etiquettes (id, nom) values (4, 'poulet');
insert into etiquettes (id, nom) values (5, 'agneau');
insert into etiquettes (id, nom) values (6, 'sucré');
insert into etiquettes (id, nom) values (7, 'salé');
insert into etiquettes (id, nom) values (8, 'piquant');
insert into etiquettes (id, nom) values (9, 'chaud');
insert into etiquettes (id, nom) values (10, 'froid');
insert into etiquettes (id, nom) values (11, 'soft');
insert into etiquettes (id, nom) values (12, 'alcoolisé');
insert into etiquettes (id, nom) values (13, 'Française');
insert into etiquettes (id, nom) values (14, 'Italienne');
insert into etiquettes (id, nom) values (15, 'Méditerranéen');
insert into etiquettes (id, nom) values (16, 'Locavore');
insert into etiquettes (id, nom) values (17, 'Sans Sucre Ajouté');
insert into etiquettes (id, nom) values (18, 'Rafraîchissant');
