insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 1);
insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 1);
insert into etiquettes_plats (etiquettes_id, plats_id) values (1, 1);
insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 2);
insert into etiquettes_plats (etiquettes_id, plats_id) values (1, 2);
insert into etiquettes_plats (etiquettes_id, plats_id) values (7, 2);
insert into etiquettes_plats (etiquettes_id, plats_id) values (16, 2);
insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 3);
insert into etiquettes_plats (etiquettes_id, plats_id) values (7, 3);
insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 3);
insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 4);
insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 4);
insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 4);
insert into etiquettes_plats (etiquettes_id, plats_id) values (13, 4);
insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 5);
insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 6);
insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 6);
insert into etiquettes_plats (etiquettes_id, plats_id) values (12, 6);
insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 7);
insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 8);
insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 8);
insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 9);
insert into etiquettes_plats (etiquettes_id, plats_id) values (18, 9);
insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 10);
insert into etiquettes_plats (etiquettes_id, plats_id) values (18, 10);
insert into etiquettes_plats (etiquettes_id, plats_id) values (18, 11);
insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 12);
insert into etiquettes_plats (etiquettes_id, plats_id) values (18, 12);
insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 13);
insert into etiquettes_plats (etiquettes_id, plats_id) values (8, 14);
insert into etiquettes_plats (etiquettes_id, plats_id) values (2, 15);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (1, 14);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (8, 15);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 14);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 15);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 16);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (7, 17);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (4, 17);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (1, 18);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (14, 19);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (1, 19);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (15, 19);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (11, 20);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (4, 21);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 21);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (11, 21);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 22);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (2, 22);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 23);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (2, 23);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (3, 23);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (4, 23);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 24);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (5, 24);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (3, 24);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 25);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (2, 25);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (1, 25);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (3, 25);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (8, 25);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 26);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (8, 26);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (2, 26);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 27);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (4, 27);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (5, 27);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 28);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (4, 28);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 29);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (16, 29);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 30);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (14, 30);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 31);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (13, 31);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (3, 31);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 32);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (14, 32);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 33);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 33);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (17, 33);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 34);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 34);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 35);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 35);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 36);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 36);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 37);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 37);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 38);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 38);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (9, 39);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 39);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (10, 40);
-- insert into etiquettes_plats (etiquettes_id, plats_id) values (6, 40);
